version: '3.8'

services:
  scraper:
    build: .
    ports:
      - "7869:7869"    
    restart: unless-stopped
    container_name: shopee_scraper_api_dev
    command: uvicorn app:app --host 0.0.0.0 --port 7869 --reload
